### ISSUE TITLE
Keystone links are not handled properly

### ISSUE THREAD

**Issue by xeropresence** [Jaliborc/LibItemCache-2.0#11]
This is the cause for 

https://github.com/tullamods/Bagnon/issues/785

Looks like 
https://github.com/Jaliborc/LibItemCache-2.0/blob/master/LibItemCache-2.0.lua#L267
Fails to process keystone items as 
GetItemInfo will return nil for a item.link such as 

link="|cffa335ee|Hkeystone:158923:248:14:10:5:13:16|h[Keystone: Waycrest Manor (14)]|h|r",

Some useful info perhaps from the raider.io addon, patterns for the m+ keystone item.
		local KEYSTONE_PATTERNS = {
			"keystone:%d+:(.-):(.-):(.-):(.-):(.-)",
			"item:158923:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:(.-):(.-):(.-):(.-):(.-):(.-)"
		}

I have deployed this change locally, and while it will let you search for "mythic","keystone" you cannot search for the dungeon name or level.

https://github.com/xeropresence/LibItemCache-2.0/commit/052d4934e90ce732216c7f38ea21bc50e04cf748

**Comment by tommimarkus** [comment]
tried a dirty fix of `partial = partial:gsub('keystone:', 'item:')` in the function `Lib:RestoreLinkData(partial)` and it seems to work. probably not the best way to do this, but at least it exposes the problem, GetItemInfo* has been broken in 8.3 for keystones

**Comment by Jaliborc** [comment]
Should be fixed with current build. Now always ignores keystone links and just uses the itemID
